version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    hostname: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9600:9600
  wazuh-manager-master:
    build:
      context: ./images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${ELASTIC_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${ELASTIC_VERSION}
    hostname: ${WAZUH_MANAGER_IMAGE}-${WAZUH_VERSION}-${ELASTIC_VERSION}
    volumes:
      - "./config/filebeat/filebeat.basic.yml:/etc/filebeat/filebeat.yml"
    ports:
      - "514:514"
      - "1514:1514"
      - "1515:1515"
      - "1516:1516"
      - "55000:55000"
    depends_on:
      - elasticsearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: master-node
      NODE_TYPE: master
  wazuh-manager-worker:
    build:
      context: ./images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${ELASTIC_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${ELASTIC_VERSION}
    hostname: ${WAZUH_MANAGER_IMAGE}-worker-${WAZUH_VERSION}-${ELASTIC_VERSION}
    volumes:
      - "./config/filebeat/filebeat.basic.yml:/etc/filebeat/filebeat.yml"
    # ports:
    #   - "514:514"
    #   - "1514:1514"
    #   - "1515:1515"
    #   - "1516:1516"
    #   - "55000:55000"
    depends_on:
      - elasticsearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: worker-node
      NODE_TYPE: worker
  wazuh-agent:
    build:
      context: ./images/${WAZUH_AGENT_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
    image: ${WAZUH_AGENT_IMAGE}:${WAZUH_VERSION}
    hostname: ${WAZUH_AGENT_IMAGE}-${WAZUH_VERSION}
    environment:
      JOIN_MANAGER: wazuh-manager-master
    depends_on:
      - wazuh-manager-master
  kibana-dev:
    build:
      context: "./images/${KIBANA_DEV_IMAGE}"
      args:
        KIBANA_BRANCH: ${KIBANA_BRANCH}
        NVM_BRANCH: ${NVM_BRANCH}
    image: ${KIBANA_DEV_IMAGE}:${KIBANA_BRANCH}
    hostname: ${KIBANA_DEV_IMAGE}:${KIBANA_BRANCH}
    ports:
      - "5601:5601"
    volumes:
      - "./config/kibana/kibana.basic.yml:/usr/share/kibana/config/kibana.yml"
      - "../../../../.:/usr/share/kibana/plugins/wazuh/"
    tty: true