---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      internal_auth:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      saml_auth:
        order: 1
        description: "SAML provider"
        http_enabled: true
        transport_enabled: false
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: http://SAML-IdP:8080/simplesaml/saml2/idp/metadata.php #SAML's metadata url, provided by your IdP
              entity_id: http://localhost:8080/simplesaml/saml2/idp/metadata.php #SAML's IdP entity ID, provided by your IdP
            sp:
              entity_id: SAML-Demo-ID
              forceAuthn: true
            kibana_url: http://localhost:5601
            subject_key: UserID
            roles_key: Role
            exchange_key: 1a2a3a4a5a6a7a8a9a0a1b2b3b4b5b6b
        authentication_backend:
          type: noop
