version: "3.7"

services:
  opensearch_dashboards:
    hostname: "opensearch_dashboards"
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_VERSION}
    volumes:
      - "../../../config/opensearch_dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
      - "${APP_PACKAGES_PATH}:/packages"
    ports:
      - "5601:5601"
  opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
    hostname: opensearch01
    environment:
      - node.name=opensearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - compatibility.override_main_response_version=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9600:9600
  wazuh-manager-master:
    build:
      context: ../../../images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${FILEBEAT_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${FILEBEAT_VERSION}
    hostname: ${WAZUH_MANAGER_IMAGE}-${WAZUH_VERSION}-${FILEBEAT_VERSION}
    volumes:
      - "../../../config/filebeat/filebeat.opensearch.yml:/etc/filebeat/filebeat.yml"
    ports:
      - "514:514"
      - "1514:1514"
      - "1515:1515"
      - "1516:1516"
      - "55000:55000"
    depends_on:
      - opensearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: master-node
      NODE_TYPE: master
  wazuh-manager-worker:
    build:
      context: ../../../images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${FILEBEAT_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${FILEBEAT_VERSION}
    hostname: ${WAZUH_MANAGER_IMAGE}-worker-${WAZUH_VERSION}-${FILEBEAT_VERSION}
    volumes:
      - "../../../config/filebeat/filebeat.opensearch.yml:/etc/filebeat/filebeat.yml"
    # ports:
    #   - "514:514"
    #   - "1514:1514"
    #   - "1515:1515"
    #   - "1516:1516"
    #   - "55000:55000"
    depends_on:
      - opensearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: worker-node
      NODE_TYPE: worker
  wazuh-agent:
    build:
      context: ../../../images/${WAZUH_AGENT_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
    image: ${WAZUH_AGENT_IMAGE}:${WAZUH_VERSION}
    hostname: ${WAZUH_AGENT_IMAGE}-${WAZUH_VERSION}
    environment:
      JOIN_MANAGER: wazuh-manager-master
    depends_on:
      - wazuh-manager-master
