version: "3.7"

services:
  wazuh-manager-master:
    build:
      context: ./images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${ELASTIC_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${ELASTIC_VERSION}
    hostname: ${WAZUH_MANAGER_IMAGE}-${WAZUH_VERSION}-${ELASTIC_VERSION}
    volumes:
      - "./config/filebeat/filebeat.odfe.yml:/etc/filebeat/filebeat.yml"
    ports:
      - "514:514"
      - "1514:1514"
      - "1515:1515"
      - "1516:1516"
      - "55000:55000"
    depends_on:
      - elasticsearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: manager-node
      NODE_TYPE: master
  wazuh-manager-worker:
    build:
      context: ./images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${ELASTIC_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${ELASTIC_VERSION}
    hostname: ${WAZUH_MANAGER_IMAGE}-worker-${WAZUH_VERSION}-${ELASTIC_VERSION}
    volumes:
      - "./config/filebeat/filebeat.odfe.yml:/etc/filebeat/filebeat.yml"
    # ports:
    #   - "514:514"
    #   - "1514:1514"
    #   - "1515:1515"
    #   - "1516:1516"
    #   - "55000:55000"
    depends_on:
      - elasticsearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: worker-node
      NODE_TYPE: worker
  wazuh-agent:
    build:
      context: ./images/${WAZUH_AGENT_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
    image: ${WAZUH_AGENT_IMAGE}:${WAZUH_VERSION}
    hostname: ${WAZUH_AGENT_IMAGE}-${WAZUH_VERSION}
    environment:
      JOIN_MANAGER: wazuh-manager-master
    depends_on:
      - wazuh-manager-master
  elasticsearch:
    image: "amazon/opendistro-for-elasticsearch:${ODFE_VERSION}"
    hostname: "elasticsearch"
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - "discovery.type=single-node"
  kibana-dev:
    build:
      context: "./images/${KIBANA_DEV_IMAGE}"
      args:
        KIBANA_BRANCH: ${KIBANA_BRANCH}
        NVM_BRANCH: ${NVM_BRANCH}
        ODFE_BRANCH: ${ODFE_BRANCH}
    image: ${KIBANA_DEV_IMAGE}:${ODFE_BRANCH}
    hostname: ${KIBANA_DEV_IMAGE}:${ODFE_BRANCH}
    ports:
      - "5601:5601"
    volumes:
      - "./config/kibana/kibana.odfe.yml:/usr/share/kibana/config/kibana.yml"
      - "../../../../.:/usr/share/kibana/plugins/wazuh/"
    tty: true