version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    hostname: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/elasticsearch/elasticsearch.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./setup/certs:$CERTS_DIR"
      - "./setup/elastic_passwords.txt:/tmp/elastic_passwords.txt"
    ports:
      - 9200:9200
      - 9600:9600
  wazuh-manager-master:
    build:
      context: ../../../images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${ELASTIC_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${ELASTIC_VERSION}
    hostname: wazuh-manager-master-${WAZUH_VERSION}-${ELASTIC_VERSION}
    volumes:
      - "../../../config/filebeat/filebeat.xpack.yml:/etc/filebeat/filebeat.yml"
      - "./setup/certs/wazuh-manager-master/wazuh-manager-master.crt:/etc/filebeat/certs/instance.crt:ro"
      - "./setup/certs/wazuh-manager-master/wazuh-manager-master.key:/etc/filebeat/certs/instance.key:ro"
      - "./setup/certs/ca/ca.crt:/etc/filebeat/certs/ca.crt:ro"
    ports:
      - "514:514"
      - "1514:1514"
      - "1515:1515"
      - "1516:1516"
      - "55000:55000"
    depends_on:
      - elasticsearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: master-node
      NODE_TYPE: master
  wazuh-manager-worker:
    build:
      context: ../../../images/${WAZUH_MANAGER_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
        FILEBEAT_VERSION: ${ELASTIC_VERSION}
        FILEBEAT_WAZUH_TEMPLATE_URL: ${FILEBEAT_WAZUH_TEMPLATE_URL}
        FILEBEAT_WAZUH_MODULE_URL: ${FILEBEAT_WAZUH_MODULE_URL}
    image: ${WAZUH_MANAGER_IMAGE}:${WAZUH_VERSION}-${ELASTIC_VERSION}
    hostname: wazuh-manager-worker-${WAZUH_VERSION}-${ELASTIC_VERSION}
    volumes:
      - "../../../config/filebeat/filebeat.xpack.yml:/etc/filebeat/filebeat.yml"
      - "./setup/certs/wazuh-manager-worker/wazuh-manager-worker.crt:/etc/filebeat/certs/instance.crt:ro"
      - "./setup/certs/wazuh-manager-worker/wazuh-manager-worker.key:/etc/filebeat/certs/instance.key:ro"
      - "./setup/certs/ca/ca.crt:/etc/filebeat/certs/ca.crt:ro"
    # ports:
    #   - "514:514"
    #   - "1514:1514"
    #   - "1515:1515"
    #   - "1516:1516"
    #   - "55000:55000"
    depends_on:
      - elasticsearch
    environment:
      NODE_IP: wazuh-manager-master
      NODE_NAME: worker-node
      NODE_TYPE: worker
  wazuh-agent:
    build:
      context: ../../../images/${WAZUH_AGENT_IMAGE}
      args: 
        WAZUH_VERSION: ${WAZUH_VERSION}
    image: ${WAZUH_AGENT_IMAGE}:${WAZUH_VERSION}
    hostname: ${WAZUH_AGENT_IMAGE}-${WAZUH_VERSION}
    environment:
      JOIN_MANAGER: wazuh-manager-master
    depends_on:
      - wazuh-manager-master
  kibana:
    hostname: "kibana"
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    volumes:
      - "../../../config/kibana/kibana.xpack.yml:/usr/share/kibana/config/kibana.yml"
      - "./setup/certs:/etc/kibana/certs:ro"
      - "$APP_PACKAGES_PATH:/packages:ro"
    ports:
      - "5601:5601"
