server.host: "0.0.0.0"
elasticsearch.hosts: "https://elasticsearch:9200"

#X-Pack
xpack.security.enabled: true
elasticsearch.username: kibana_system
elasticsearch.password: kibana_system

elasticsearch.ssl.certificateAuthorities: /etc/kibana/certs/ca/ca.crt
elasticsearch.ssl.certificate: /etc/kibana/certs/elasticsearch/elasticsearch.crt
elasticsearch.ssl.key: /etc/kibana/certs/elasticsearch/elasticsearch.key

# Browser from/to Kibana
server.ssl.enabled: true
server.ssl.certificate: /etc/kibana/certs/kibana/kibana.crt
server.ssl.key: /etc/kibana/certs/kibana/kibana.key